Change logging calls

diff --git a/run-dotbot b/run-dotbot
--- a/run-dotbot
+++ b/run-dotbot
@@ -32,7 +32,7 @@ else
   if [ $exit_code -eq 0 ]; then
     log_success "Dotbot update successful"
   else
-    log_failure "Dotbot update failed"
+    log_fatal "Dotbot update failed"
     return 1
   fi
 fi
@@ -47,7 +47,7 @@ typeset -gx XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
 CONFIG="dotbot.conf.yaml"
 
 if [[ ! -s "$CONFIG" ]]; then
-  log_failure "Dotbot config file '$CONFIG' is missing or empty!" >&2
+  log_fatal "Dotbot config file '$CONFIG' is missing or empty!" >&2
   return 1
 fi
 
@@ -60,7 +60,7 @@ if [[ -s "$CONFIG" ]]; then
       if brew install gettext 2>&1 | output_stream; then
         log_success "gettext installed successfully!"
       else
-        log_failure "gettext installation failed!"
+        log_fatal "gettext installation failed!"
         return 1
       fi
     fi
@@ -87,7 +87,7 @@ if [[ -s "$CONFIG" ]]; then
       rm -f "$TMPFILE"
       
     else
-      log_failure "envsubst not found. Please install gettext."
+      log_fatal "envsubst not found. Please install gettext."
       return 1
     fi
 
@@ -102,6 +102,6 @@ if [[ -s "$CONFIG" ]]; then
     echo "$output" | output_stream 2>/dev/null
   fi
 else
-  log_failure "Config file $CONFIG is missing or empty!"
+  log_fatal "Config file $CONFIG is missing or empty!"
   return 1
 fi
